# Generated by Django 5.0.7 on 2024-08-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restoran_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_text', models.TextField()),
                ('image', models.ImageField(upload_to='about_images/')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='quantitiy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishes_about',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
