# Generated by Django 5.0.7 on 2024-08-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restoran_about_rename_customer_name_order_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restoran_about',
        ),
    ]
