# Generated by Django 5.0.7 on 2024-08-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_restoran_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
