# Generated by Django 5.0.7 on 2024-08-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='dishes_about',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='name',
            new_name='title',
        ),
    ]
