# Generated by Django 5.0.7 on 2024-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_dishes_about_dishes_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='text',
        ),
        migrations.AddField(
            model_name='dishes',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
