# Generated by Django 5.0.7 on 2024-08-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_delete_dishesimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Food',
        ),
    ]
